# tests/test_startup_promotion.py
import json
from pathlib import Path
import yaml
from compchem_memory import startup_scan


def _proposal_artifact(store, name, pending):
    """Write a proposal artifact with one proposal that is either pending
    (unhandled) or fully handled (applied)."""
    art = store / "reflex" / name
    art.parent.mkdir(parents=True, exist_ok=True)
    data = {"proposals": [{"k": 1}], "applied": [], "rejected": []}
    if not pending:
        data["applied"] = [0]
    art.write_text(json.dumps(data))


def _entry(entries, name, title, sessions):
    fm = {"title": title, "type": "success_pattern",
          "observed_in_sessions": sessions, "confidence": 0.9}
    (entries / name).write_text("---\n" + yaml.dump(fm) + "---\n\nbody\n")


def test_maybe_promote_runs_when_llm_available(tmp_path, monkeypatch):
    store = tmp_path / ".magnolia"; entries = store / "entries"; entries.mkdir(parents=True)
    _entry(entries, "a.md", "Alpha", ["s1", "s2", "s3"])
    monkeypatch.setattr(startup_scan, "is_llm_available", lambda: True)
    called = {}
    def fake_propose(store_dir, *, rules_dir):
        called["store"] = store_dir; return {"candidates": 0}
    monkeypatch.setattr("compchem_memory.promotion.propose_promotions", fake_propose)

    startup_scan._maybe_promote(store)
    assert called["store"] == str(store)


def test_maybe_promote_skips_without_llm(tmp_path, monkeypatch):
    store = tmp_path / ".magnolia"; (store / "entries").mkdir(parents=True)
    monkeypatch.setattr(startup_scan, "is_llm_available", lambda: False)
    startup_scan._maybe_promote(store)        # must not raise, must not call LLM


def test_maybe_promote_frozen_while_review_pending(tmp_path, monkeypatch):
    # A pending promotion review must NOT be regenerated by a sweep — otherwise the
    # index the user reviewed could point at a different proposal at apply time.
    store = tmp_path / ".magnolia"; entries = store / "entries"; entries.mkdir(parents=True)
    _entry(entries, "a.md", "Alpha", ["s1", "s2", "s3"])
    _proposal_artifact(store, "promotion-proposal.json", pending=True)
    monkeypatch.setattr(startup_scan, "is_llm_available", lambda: True)
    calls = {"n": 0}
    monkeypatch.setattr("compchem_memory.promotion.propose_promotions",
                        lambda *a, **k: calls.__setitem__("n", calls["n"] + 1))
    startup_scan._maybe_promote(store)
    assert calls["n"] == 0                     # frozen — no regeneration


def test_maybe_promote_regenerates_when_nothing_pending(tmp_path, monkeypatch):
    store = tmp_path / ".magnolia"; entries = store / "entries"; entries.mkdir(parents=True)
    _entry(entries, "a.md", "Alpha", ["s1", "s2", "s3"])
    _proposal_artifact(store, "promotion-proposal.json", pending=False)  # all handled
    monkeypatch.setattr(startup_scan, "is_llm_available", lambda: True)
    calls = {"n": 0}
    def fake(store_dir, *, rules_dir):
        calls["n"] += 1; return {"candidates": 0}
    monkeypatch.setattr("compchem_memory.promotion.propose_promotions", fake)
    startup_scan._maybe_promote(store)
    assert calls["n"] == 1                      # safe to regenerate when nothing pending


def test_maybe_consolidate_frozen_while_review_pending(tmp_path, monkeypatch):
    store = tmp_path / ".magnolia"; (store / "staging").mkdir(parents=True)
    _proposal_artifact(store, "consolidation-proposal.json", pending=True)
    monkeypatch.setattr(startup_scan, "is_llm_available", lambda: True)
    calls = {"n": 0}
    monkeypatch.setattr("compchem_memory.consolidation.consolidate_project_findings",
                        lambda *a, **k: calls.__setitem__("n", calls["n"] + 1))
    startup_scan._maybe_consolidate(store)
    assert calls["n"] == 0                      # frozen — guard runs before the count check
